### ISSUE TITLE
pb rocher

### ISSUE THREAD

**Issue by TheultimateZank** [Webrom/Projet_JAVA#4]
le rocher tombe pas si y a un diamant au dessus
![capture du 2015-06-19 18 49 20](https://cloud.githubusercontent.com/assets/12337798/8258278/ee247288-16b3-11e5-9590-ca639d4a471d.png)

**Comment by Webrom** [comment]
Assez incompréhensible... Je regarde ça demain.

**Comment by Webrom** [comment]
J'ai trouvé le problème... Du coup pour éviter de faire descendre l'objet d'un coup j'ai fait un i++ dans la matrice... Mais du coup elle ne scrute plus le boulder dans ce cas. 
Je vais réfléchir à une solution.

**Comment by Webrom** [comment]
Alors ce problème est solutionné... Mais du coup le magic wall ne fonctionne plus... Mais fonctions sont superbes !
